### ISSUE TITLE
Eager loading deeply nested relations

### ISSUE THREAD

**Issue by priithansen** [gurucomkz/silverstripe-eagerloading#1]
Hi thank You for this easy to use package.

I was wondering if it is possible to also eager load deeply nested relations?
`For example: Inspection has_one -> Device has_one ->  Contract `
Something like this doesn't seem work also tried nested arrays with different errors.
`Inspection::get()->with(['Device.Contract'])`

Fingers crossed it's documentation issue 🤞 🙂

**Comment by gurucomkz** [comment]
Hi @priithansen ,
Sorry for the late reply.

Yes this should work.
Can you, please, elaborate on what effects you are having when executing this code?

**Comment by priithansen** [comment]
Hi and thanks for looking into this.

It indeed seems my errors are caused by trying to eager load a polymorphic relation. Not sure if there is anything this addon can do in this situation.

As the last has_one on the chain is polymorphic
```php
private static $has_one = [
    'DeviceOf' => DataObject::class, // Zone or Output
];
```
and I'm trying to eager load it with
```php
DeviceInspection::get()->with(['Device.DeviceOf'])
```
![Screenshot 2021-02-07 at 14 55 08](https://user-images.githubusercontent.com/1476082/107147328-209a0200-6956-11eb-960c-dda676415eb6.png)

**Comment by gurucomkz** [comment]
This has nothing to do with the module, sorry.
AFAIK, DataObject is not an end-user class in SS4 and has no DB table, therefore no lookup queries are possible.

I highly recommend to create a parent class for all the possible options behind DeviceOf and use it there.
i.e.

```php
class DeviceConnection extends DataObject {}

class Zone extends DeviceConnection {}
class Output extends DeviceConnection {}
```
and then
```php
class Device extends DataObject {
    private static $has_one = [
         'DeviceOf' => DeviceConnection::class, // Zone or Output
    ];
}

**Comment by priithansen** [comment]
Thought so, thanks for the tip about using a common parent class and also in hindsight I should have probably just used one class with a type enum :) 

Thank You for Your time and thoughts!
