### ISSUE TITLE
Fails with PostgreSQLDatabase

### ISSUE THREAD

**Issue by sanderha** [gurucomkz/silverstripe-eagerloading#4]
Very nice module, first of all. I am using the official PostgreSQL package, and it looks like this package is not compatible.
More specifically, the customer SELECT's made in the eager loading methods. They work with MySQL because MySQL maintains given case on the input, while Postgres lowercases all these strings (table names, columns).

For example in `EagerLoadedDataList::eagerLoadHasOne()`, the following will fail in Postgres:
```php
        //collect required IDS
        $fields = ['ID'];
        foreach ($withHasOnes as $depSeq) {
            $dep = $depSeq[0];
            $fields[] = "{$dep}ID";
        }
        $table = Config::forClass($this->dataClass)->get('table_name');
        $data = new SQLSelect(implode(',', $fields), [$table], ["ID IN (" . implode(',', $ids) . ")"]);
        $data = Utils::EnsureArray($data->execute(), 'ID');
 ```  
 While this will make it work:
 ```php
         $fields = ['"ID"'];
        foreach ($withHasOnes as $depSeq) {
            $dep = $depSeq[0];
            $fields[] = "\"{$dep}ID\"";
        }
        $table = Config::forClass($this->dataClass)->get('table_name');
        $data = new SQLSelect(implode(',', $fields), ['"'.$table.'"'], ["\"ID\" IN (" . implode(',', $ids) . ")"]);
        $data = Utils::EnsureArray($data->execute(), 'ID')
 ```
 as double quotes will make Postgress respect casing. 
 
 I dont have time to make a proper Postgress compatible PR at the moment, but I thought I'd make this issue

**Comment by gurucomkz** [comment]
Good point! Thank you, I'll work on that.
